#!/bin/sh

INDIR=`dirname $0`
DEST=$1
shift

if [ -z "$HDR" ]; then
    HDR="HDR"
fi

basename=`basename $0`
echo "// DO NOT EDIT THIS FILE - IT WAS AUTOGENERATED BY $basename FROM rules/*.part" >$DEST

for i in $*; do
  if [ "$i" = "$HDR" ] || [ "$i" = "HDR" ]; then
    echo >> $DEST;
    read hdr
    echo "$hdr" >> $DEST
  elif test -f $i; then
    cat $i >> $DEST || exit 1
  else
    cat $INDIR/$i >> $DEST || exit 1
  fi
done < $HDR

