#!/bin/bash

DEST=$1
shift

if [ -z "$HDR" ]; then
    HDR="HDR"
fi

basename=`basename $0`
echo "// DO NOT EDIT THIS FILE - IT WAS AUTOGENERATED BY $basename FROM rules/*.part" >$DEST

for i in $*; do
  if [ "$i" == "$HDR" ] || [ "$i" == "HDR" ]; then
    echo >> $DEST;
    read hdr
    echo "$hdr" >> $DEST
  else
    cat $i >> $DEST;
  fi
done < $HDR

