LIBRARY = libtype1

CSRCS =			\
		arith.c			\
		curves.c		\
		fontfcn.c		\
		hints.c			\
		lines.c			\
		objects.c		\
		paths.c			\
		regions.c		\
		scanfont.c		\
		spaces.c		\
		t1funcs.c		\
		t1info.c		\
		t1io.c			\
		t1malloc.c		\
		t1snap.c		\
		t1unicode.c		\
		token.c			\
		type1.c			\
		util.c

INCLUDES := ../../../../build $(INCLUDES)

