LIBRARY=librandr

CSRCS =	\
 rrxinerama.c	\
	mirandr.c	\
	randr.c		\
	rrcrtc.c	\
	rrdispatch.c	\
	rrinfo.c	\
	rrmode.c	\
	rroutput.c	\
	rrpointer.c	\
	rrproperty.c	\
	rrscreen.c	\
	rrsdispatch.c	\
	rrtransform.c

