LIBRARY=libXpm

INCLUDES += ..\include\X11

CSRCS =					\
	Attrib.c					\
	CrBufFrI.c					\
	CrBufFrP.c					\
	CrDatFrI.c					\
	CrDatFrP.c					\
	CrIFrBuf.c					\
	CrIFrDat.c					\
	CrIFrP.c					\
	CrPFrBuf.c					\
	CrPFrDat.c					\
	CrPFrI.c					\
	Image.c						\
	Info.c						\
	RdFToBuf.c					\
	RdFToDat.c					\
	RdFToI.c					\
	RdFToP.c					\
	WrFFrBuf.c					\
	WrFFrDat.c					\
	WrFFrI.c					\
	WrFFrP.c					\
	create.c					\
	data.c						\
	hashtab.c					\
	misc.c						\
	parse.c						\
	rgb.c						\
	scan.c

