fcg xserver            ..\released\xorg-server             
fcg libxcb             ..\released\libxcb          
fcg xkeyboard-config   ..\released\xorg-server\xkeyboard-config
fcg libX11             ..\released\libX11          
fcg libXdmcp           ..\released\libXdmcp        
fcg libXext            ..\released\libXext         
fcg libfontenc         ..\released\libfontenc      
fcg libXinerama        ..\released\libXinerama     
fcg libXau             ..\released\libXau          
fcg xkbcomp            ..\released\xkbcomp         
fcg pixman             ..\released\pixman          
fcg xextproto          ..\released\X11\extensions       
fcg randrproto         ..\released\X11\extensions
