fc .\libX11\include\X11\cursorfont.h .\X11\cursorfont.h
fc .\include\xcb\xcbext.h .\libxcb\src\xcbext.h
fc .\include\xcb\render.h .\libxcb\src\render.h
fc .\libX11\include\X11\Xlocale.h .\X11\Xlocale.h
fc .\libXau\include\X11\Xauth.h  .\X11\Xauth.h 
fc .\libX11\include\X11\XKBlib.h .\X11\XKBlib.h
fc .\libXinerama\include\X11\extensions\panoramiXext.h   .\X11\extensions\panoramiXext.h
fc .\libXdmcp\include\X11\Xdmcp.h   .\X11\Xdmcp.h
fc .\libXinerama\include\X11\extensions\Xinerama.h   .\X11\extensions\Xinerama.h
fc .\include\xcb\xcb.h   .\libxcb\src\xcb.h
fc .\libX11\include\X11\Xlibint.h   .\X11\Xlibint.h
fc .\include\xcb\xproto.h   .\libxcb\src\xproto.h
fc .\libX11\include\X11\Xutil.h   .\X11\Xutil.h
fc .\gl\glcore.h   .\gl\internal\glcore.h
fc .\include\xcb\xc_misc.h   .\libxcb\src\xc_misc.h
fc .\libX11\include\X11\Xlib.h      .\X11\Xlib.h     
fc .\libX11\include\X11\Xresource.h .\X11\Xresource.h
fc .\libX11\include\X11\Xlib-xcb.h  .\X11\Xlib-xcb.h 
fc .\include\xcb\bigreq.h   .\libxcb\src\bigreq.h
fc .\libX11\include\X11\Xcms.h    .\X11\Xcms.h   
fc .\libX11\include\X11\Xregion.h .\X11\Xregion.h
fc .\libX11\include\X11\ImUtil.h  .\X11\ImUtil.h 
fc .\gl\glext.h                  .\mesalib\include\gl\glext.h
fc .\gl\glx.h                    .\mesalib\include\gl\glx.h
fc .\gl\glxext.h                 .\mesalib\include\gl\glxext.h
fc .\gl\glx_mangle.h             .\mesalib\include\gl\glx_mangle.h
fc .\gl\gl_mangle.h              .\mesalib\include\gl\gl_mangle.h
fc .\gl\internal\dri_interface.h .\mesalib\include\gl\internal\dri_interface.h
fc .\gl\internal\glcore.h        .\mesalib\include\gl\internal\glcore.h
fc libXt\include\X11\CallbackI.h  .\X11\CallbackI.h
fc libXt\include\X11\Composite.h  .\X11\Composite.h  
fc libXt\include\X11\CompositeP.h .\X11\CompositeP.h 
fc libXt\include\X11\ConstrainP.h .\X11\ConstrainP.h 
fc libXt\include\X11\Constraint.h .\X11\Constraint.h 
fc libXt\include\X11\ConvertI.h   .\X11\ConvertI.h   
fc libXt\include\X11\Core.h       .\X11\Core.h       
fc libXt\include\X11\CoreP.h      .\X11\CoreP.h      
fc libXt\include\X11\CreateI.h    .\X11\CreateI.h    
fc libXt\include\X11\EventI.h     .\X11\EventI.h     
fc libXt\include\X11\HookObjI.h   .\X11\HookObjI.h   
fc libXt\include\X11\InitialI.h   .\X11\InitialI.h   
fc libXt\include\X11\Intrinsic.h  .\X11\Intrinsic.h  
fc libXt\include\X11\IntrinsicI.h .\X11\IntrinsicI.h 
fc libXt\include\X11\IntrinsicP.h .\X11\IntrinsicP.h 
fc libXt\include\X11\Object.h     .\X11\Object.h     
fc libXt\include\X11\ObjectP.h    .\X11\ObjectP.h    
fc libXt\include\X11\PassivGraI.h .\X11\PassivGraI.h 
fc libXt\include\X11\RectObj.h    .\X11\RectObj.h    
fc libXt\include\X11\RectObjP.h   .\X11\RectObjP.h   
fc libXt\include\X11\ResConfigP.h .\X11\ResConfigP.h 
fc libXt\include\X11\ResourceI.h  .\X11\ResourceI.h  
fc libXt\include\X11\SelectionI.h .\X11\SelectionI.h 
fc libXt\include\X11\Shell.h      .\X11\Shell.h      
fc libXt\include\X11\ShellI.h     .\X11\ShellI.h     
fc libXt\include\X11\ShellP.h     .\X11\ShellP.h     
fc libXt\include\X11\StringDefs.h .\X11\StringDefs.h 
fc libXt\include\X11\ThreadsI.h   .\X11\ThreadsI.h   
fc libXt\include\X11\TranslateI.h .\X11\TranslateI.h 
fc libXt\include\X11\VarargsI.h   .\X11\VarargsI.h   
fc libXt\include\X11\Vendor.h     .\X11\Vendor.h     
fc libXt\include\X11\VendorP.h    .\X11\VendorP.h    
fc libXt\include\X11\Xtos.h       .\X11\Xtos.h       
                                       