fcg .\libX11\include\X11\cursorfont.h .\X11
fcg .\include\xcb\xcbext.h .\libxcb\src
fcg .\include\xcb\render.h .\libxcb\src
fcg .\libX11\include\X11\Xlocale.h .\X11
fcg .\libXau\include\X11\Xauth.h .\X11
fcg .\libX11\include\X11\XKBlib.h   .\X11
fcg .\libXinerama\include\X11\extensions\panoramiXext.h   .\X11\extensions
fcg .\libXdmcp\include\X11\Xdmcp.h   .\X11
fcg .\libXinerama\include\X11\extensions\Xinerama.h   .\X11\extensions
fcg .\include\xcb\xcb.h   .\libxcb\src
fcg .\libX11\include\X11\Xlibint.h   .\X11
fcg .\include\xcb\xproto.h   .\libxcb\src
fcg .\libX11\include\X11\Xutil.h   .\X11
fcg .\gl\glcore.h   .\gl\internal
fcg .\include\xcb\xc_misc.h   .\libxcb\src
fcg .\libX11\include\X11\Xlib.h  .\X11
fcg .\libX11\include\X11\Xresource.h   .\X11
fcg .\libX11\include\X11\Xlib-xcb.h   .\X11
fcg .\include\xcb\bigreq.h   .\libxcb\src
fcg .\libX11\include\X11\Xcms.h   .\X11
fcg .\libX11\include\X11\Xregion.h   .\X11
fcg .\libX11\include\X11\ImUtil.h   .\X11
fcg .\gl\glext.h                  .\mesalib\include\gl\glext.h
fcg .\gl\glx.h                    .\mesalib\include\gl\glx.h
fcg .\gl\glxext.h                 .\mesalib\include\gl\glxext.h
fcg .\gl\glx_mangle.h             .\mesalib\include\gl\glx_mangle.h
fcg .\gl\gl_mangle.h              .\mesalib\include\gl\gl_mangle.h
fcg .\gl\internal\dri_interface.h .\mesalib\include\gl\internal\dri_interface.h
fcg .\gl\internal\glcore.h        .\mesalib\include\gl\internal\glcore.h
