LIBRARY=libexa

CSRCS = \
	exa.c \
	exa_classic.c \
	exa_migration_classic.c \
	exa_driver.c \
	exa_mixed.c \
	exa_migration_mixed.c \
	exa_accel.c \
	exa_glyphs.c \
	exa_offscreen.c \
	exa_render.c \
	exa_unaccel.c
