DEFINES += XIM_t TRANS_CLIENT

LIBRARY=libximcp

DEFINES += LIB11_DLL

CSRCS = \
	imCallbk.c \
	imDefFlt.c \
	imDefIc.c \
	imDefIm.c \
	imDefLkup.c \
	imDispch.c \
	imEvToWire.c \
	imExten.c \
	imImSw.c \
	imInsClbk.c \
	imInt.c \
	imLcFlt.c \
	imLcGIc.c \
	imLcIc.c \
	imLcIm.c \
	imLcLkup.c \
	imLcPrs.c \
	imLcSIc.c \
	imRmAttr.c \
	imRm.c \
	imThaiFlt.c \
	imThaiIc.c \
	imThaiIm.c \
	imTrans.c \
	imTransR.c \
	imTrX.c

INCLUDES += ..\..\..\include\X11 ..\..\..\src\xlibi18n ..\..\..\src

