CSRCS=\
bigreq.c \
dpms.c \
dpmsstubs.c \
mbuf.c \
saver.c \
security.c \
shape.c \
sleepuntil.c \
sync.c \
xace.c \
xcmisc.c \
xres.c \
xtest.c \
geext.c \
panoramiX.c \
panoramiXprocs.c \
panoramiXSwap.c 

#shm.c \
#appgroup.c \
#fontcache.c \
#mbufbf.c \
#mbufpx.c \
#xcalibrate.c \
#xf86bigfont.c \
#xprint.c \
#xselinux.c \
#xvdisp.c \
#xvmain.c \
#xvmc.c

LIBRARY=libxext

INCLUDES += ..\hw\xfree86\dixmods\extmod



