CSRCS=\
bigreq.c \
cup.c \
dpms.c \
dpmsstubs.c \
EVI.c \
mbuf.c \
mitmisc.c \
sampleEVI.c \
saver.c \
security.c \
shape.c \
sleepuntil.c \
sync.c \
xace.c \
xcmisc.c \
xevie.c \
xres.c \
xtest.c

#shm.c \
#appgroup.c \
#fontcache.c \
#mbufbf.c \
#mbufpx.c \
#panoramiX.c \
#panoramiXprocs.c \
#panoramiXSwap.c \
#xcalibrate.c \
#xf86bigfont.c \
#xprint.c \
#xselinux.c \
#xvdisp.c \
#xvmain.c \
#xvmc.c

LIBRARY=libxext

INCLUDES += ..\hw\xfree86\dixmods\extmod



