DEFINES += FONTDEBUG

LIBRARY=libdix

CSRCS=\
	atom.c		\
	colormap.c	\
	cursor.c	\
	deprecated.c	\
	devices.c	\
	dispatch.c	\
	dixfonts.c	\
	dixutils.c	\
	enterleave.c	\
	events.c	\
	extension.c	\
	ffs.c		\
	gc.c		\
	getevents.c	\
	globals.c	\
	glyphcurs.c	\
	grabs.c		\
	initatoms.c	\
	main.c		\
	pixmap.c	\
	privates.c	\
	property.c	\
	ptrveloc.c	\
	registry.c	\
	resource.c	\
	selection.c	\
	swaprep.c	\
	swapreq.c	\
	tables.c	\
	window.c

