LIBRARY = libutil

INCLUDES += ../stubs

CSRCS = atom.c fontaccel.c fontnames.c fontutil.c fontxlfd.c format.c miscutil.c \
	patcache.c private.c utilbitmap.c

INCLUDES := ../../../../build $(INCLUDES)


