SHAREDLIB = libXext

INCLUDES := ..\include $(INCLUDES)

INCLUDELIBFILES =  \
 $(MHMAKECONF)\libX11\$(OBJDIR)\libX11.lib

CSRCS = \
	DPMS.c \
	MITMisc.c \
	XAppgroup.c \
	XEVI.c \
	XLbx.c \
	XMultibuf.c \
	XSecurity.c \
	XShape.c \
	XShm.c \
	XSync.c \
	XTestExt1.c \
	Xcup.c \
	Xdbe.c \
        Xge.c \
	extutil.c \
	globals.c

