
LIBRARY = libfontfile

DEFINES += X_GZIP_FONT_COMPRESSION

CSRCS = bitsource.c		\
	bufio.c			\
	decompress.c		\
	defaults.c		\
	dirfile.c		\
	fileio.c		\
	filewr.c		\
	fontdir.c		\
	fontencc.c		\
	fontfile.c		\
	fontscale.c		\
	gunzip.c		\
	register.c		\
	renderers.c		\
	catalogue.c

INCLUDES := ../.. $(INCLUDES)


