LIBRARY = libspeedo

CSRCS =			\
	adobe-iso.h			\
	bics-iso.h			\
	bics-unicode.c			\
	bics-unicode.h			\
	do_char.c			\
	do_trns.c			\
	keys.h				\
	out_bl2d.c			\
	out_blk.c			\
	out_outl.c			\
	out_scrn.c			\
	out_util.c			\
	reset.c				\
	set_spcs.c			\
	set_trns.c			\
	spdo_prv.h			\
	speedo.h			\
	spencode.c			\
	sperr.c				\
	spfile.c			\
	spfont.c			\
	spfuncs.c			\
	spglyph.c			\
	spinfo.c			\
	spint.h				\
	useropt.h
CSRCS:=$(filter-out %.h,$(CSRCS))

INCLUDES := ../../../../build $(INCLUDES)


