LIBRARY = libbitmap

CSRCS = 		\
	bdfread.c		\
	bdfutils.c		\
	bitmap.c		\
	bitmapfunc.c		\
	bitmaputil.c		\
	bitscale.c		\
	fontink.c		\
	pcfread.c		\
	pcfwrite.c		\
	snfread.c

INCLUDES := ../.. $(INCLUDES)

