LIBRARY = libi18n

INCLUDES += ..\..\include\X11 ..
DEFINES += XLOCALELIBDIR="\".\"" LIB11_DLL

CSRCS = \
	$(XI18N_DL_SOURCES) \
	XDefaultIMIF.c \
	XDefaultOMIF.c \
	xim_trans.c\
	ICWrap.c\
	IMWrap.c\
	imKStoUCS.c\
	lcCT.c\
	lcCharSet.c\
	lcConv.c\
	lcDB.c\
	lcDynamic.c\
	lcFile.c\
	lcGeneric.c\
	lcInit.c\
	lcPrTxt.c\
	lcPubWrap.c\
	lcPublic.c\
	lcRM.c\
	lcStd.c\
	lcTxtPr.c\
	lcUTF8.c\
	lcUtil.c\
	lcWrap.c\
	mbWMProps.c\
	mbWrap.c\
	utf8WMProps.c\
	utf8Wrap.c\
	wcWrap.c


