LIBRARY = libxkbfile

CSRCS =  cout.c \
         maprules.c \
         srvmisc.c \
         xkbatom.c \
         xkbbells.c \
         xkbconfig.c \
         xkbdraw.c \
         xkberrs.c \
         xkbmisc.c \
         xkbout.c \
         xkbtext.c \
         xkmout.c \
         xkmread.c

INCLUDES := . $(MHMAKECONF)\X11\extensions $(MHMAKECONF) $(MHMAKECONF)\include

