
LIBRARY=libfb

CCFLAGS:=$(CCFLAGS:-RTCc=)


CSRCS = 	\
	fb24_32.c	\
	fballpriv.c	\
	fbarc.c		\
	fbbits.c	\
	fbblt.c		\
	fbbltone.c	\
	fbcopy.c	\
	fbfill.c	\
	fbfillrect.c	\
	fbfillsp.c	\
	fbgc.c		\
	fbgetsp.c	\
	fbglyph.c	\
	fbimage.c	\
	fbline.c	\
	fboverlay.c	\
	fbpict.c	\
	fbpixmap.c	\
	fbpoint.c	\
	fbpush.c	\
	fbscreen.c	\
	fbseg.c		\
	fbsetsp.c	\
	fbsolid.c	\
	fbstipple.c	\
	fbtile.c	\
	fbtrap.c	\
	fbutil.c	\
	fbwindow.c \
	fbcmap_mi.c
