File Index
dmxbackend.h File Reference
Functions
pointer dmxBackendCreatePrivate (DeviceIntPtr pDevice)
void dmxBackendDestroyPrivate (pointer private)
void dmxBackendInit (DevicePtr pDev)
void dmxBackendLateReInit (DevicePtr pDev)
void dmxBackendMouGetInfo (DevicePtr pDev, DMXLocalInitInfoPtr info)
void dmxBackendKbdGetInfo (DevicePtr pDev, DMXLocalInitInfoPtr info)
void dmxBackendCollectEvents (DevicePtr pDev, dmxMotionProcPtr motion, dmxEnqueueProcPtr enqueue, dmxCheckSpecialProcPtr checkspecial, DMXBlockType block)
void dmxBackendProcessInput (pointer private)
int dmxBackendFunctions (pointer private, DMXFunctionType function)
void dmxBackendUpdatePosition (pointer private, int x, int y)
Detailed Description
Interface to backend input device support.
See also:
dmxbackend.c
dmxcommon.c
Function Documentation
void dmxBackendCollectEvents (DevicePtr pDev, dmxMotionProcPtr motion, dmxEnqueueProcPtr enqueue, dmxCheckSpecialProcPtr checkspecial, DMXBlockType block)
Get events from the X queue on the backend servers and put the events into the DMX event queue.
References _DMXScreenInfo::beDisplay, DMX_ABSOLUTE, DMX_RELATIVE, dmxBackendFindWindow(), dmxBackendGetEvent(), dmxBackendPendingMotionEvent(), dmxCommonRestoreState(), dmxCommonSaveState(), DMXDBG2, DMXDBG4, DMXDBG5, DMXDBG7, DMXDBG8, DMXDBG9, dmxError, dmxFatal, dmxLog(), dmxSync(), GETDMXINPUTFROMPRIV, GETPRIVFROMPDEV, _DMXScreenInfo::index, _DMXScreenInfo::name, _DMXScreenInfo::rootHeight, _DMXScreenInfo::rootWidth, _DMXScreenInfo::rootX, _DMXScreenInfo::rootXOrigin, _DMXScreenInfo::rootY, _DMXScreenInfo::rootYOrigin, and _DMXScreenInfo::scrnWin.
pointer dmxBackendCreatePrivate (DeviceIntPtr pDevice)
Create and return a private data structure.
References GETDMXLOCALFROMPDEVICE.
void dmxBackendDestroyPrivate (pointer private)
Destroy the private data structure. No checking is performed to verify that the structure was actually created by dmxBackendCreatePrivate.
int dmxBackendFunctions (pointer private, DMXFunctionType function)
Process DMXFunctionType functions. The only function handled here is to acknowledge a pending server shutdown.
References DMX_FUNCTION_TERMINATE.
void dmxBackendInit (DevicePtr pDev)
Initialized the backend device described by pDev.
References DMX_LOCAL_KEYBOARD, DMX_LOCAL_MOUSE, dmxBackendComputeCenter(), dmxBackendInitPrivate(), dmxBackendSameDisplay(), GETPRIVFROMPDEV, and _DMXScreenInfo::index.
void dmxBackendKbdGetInfo (DevicePtr pDev, DMXLocalInitInfoPtr info)
Get information about the backend keyboard (for initialization).
References dmxCommonKbdGetInfo(), dmxCommonKbdGetMap(), _DMXLocalInitInfo::focusClass, _DMXLocalInitInfo::freemap, _DMXLocalInitInfo::kbdFeedbackClass, _DMXLocalInitInfo::keyboard, _DMXLocalInitInfo::keyClass, _DMXLocalInitInfo::keySyms, and _DMXLocalInitInfo::modMap.
void dmxBackendLateReInit (DevicePtr pDev)
Re-initialized the backend device described by pDev (after a reconfig).
References dmxBackendComputeCenter(), dmxBackendInitPrivate(), dmxBackendSameDisplay(), dmxBackendUpdatePosition(), DMXDBG1, dmxGetGlobalPosition(), dmxInvalidateGlobalPosition(), and GETPRIVFROMPDEV.
void dmxBackendMouGetInfo (DevicePtr pDev, DMXLocalInitInfoPtr info)
Get information about the backend pointer (for initialization).
References _DMXScreenInfo::beHeight, _DMXScreenInfo::beWidth, _DMXLocalInitInfo::buttonClass, dmxBackendInitPrivate(), dmxCommonMouGetMap(), _DMXLocalInitInfo::map, _DMXLocalInitInfo::maxres, _DMXLocalInitInfo::maxval, _DMXLocalInitInfo::minres, _DMXLocalInitInfo::minval, _DMXLocalInitInfo::numButtons, _DMXLocalInitInfo::numRelAxes, _DMXLocalInitInfo::ptrFeedbackClass, _DMXLocalInitInfo::res, and _DMXLocalInitInfo::valuatorClass.
void dmxBackendProcessInput (pointer private)
Called after input events are processed from the DMX queue. No event processing actually takes place here, but this is a convenient place to update the pointer.
References DMXDBG4, DMXDBG6, dmxScreens, dmxSync(), and GETPRIVFROMPRIVATE.
void dmxBackendUpdatePosition (pointer private, int x, int y)
This routine is called from dmxCoreMotion for each motion event. x and y are global coordinants.
References dmxBackendFindOverlapping(), dmxBackendOffscreen(), dmxBackendPendingMotionEvent(), dmxBackendSameDisplay(), dmxCheckCursor(), dmxConsoleCapture(), dmxConsoleUncapture(), DMXDBG0, DMXDBG2, DMXDBG5, DMXDBG9, dmxHideCursor(), dmxScreens, dmxSync(), and GETPRIVFROMPRIVATE.
Referenced by dmxBackendLateReInit().
Generated June 29, 2004 for Distributed Multihead X by doxygen 1.3.4.