File Index
dmxconfig.h File Reference
#include <xkb-config.h>
Functions
void dmxConfigStoreDisplay (const char *display)
void dmxConfigStoreInput (const char *input)
void dmxConfigStoreXInput (const char *input)
void dmxConfigStoreFile (const char *file)
void dmxConfigStoreConfig (const char *config)
void dmxConfigConfigure (void)
void dmxConfigSetMaxScreens (void)
void dmxConfigSetXkbRules (const char *rules)
void dmxConfigSetXkbModel (const char *model)
void dmxConfigSetXkbLayout (const char *layout)
void dmxConfigSetXkbVariant (const char *variant)
void dmxConfigSetXkbOptions (const char *options)
char * dmxConfigGetXkbRules (void)
char * dmxConfigGetXkbModel (void)
char * dmxConfigGetXkbLayout (void)
char * dmxConfigGetXkbVariant (void)
char * dmxConfigGetXkbOptions (void)
Detailed Description
Interface for DMX configuration file support.
See also:
dmxconfig.c
Function Documentation
void dmxConfigConfigure (void)
Set up the appropriate global variables so that the DMX server will be initialized using the configuration specified in the config file and on the command line.
References DMXConfigCmdStruct::config, DMXConfigCmdStruct::displays, dmxConfigConfigInputs(), dmxConfigFreeEntry(), dmxConfigFromCommandLine(), dmxConfigFromConfigFile(), dmxConfigReadFile(), dmxLog(), dmxWarning, and DMXConfigCmdStruct::filename.
Referenced by dmxConfigSetMaxScreens(), and InitOutput().
char* dmxConfigGetXkbLayout (void)
Referenced by dmxDeviceOnOff(), and dmxKeyboardOn().
char* dmxConfigGetXkbModel (void)
Referenced by dmxDeviceOnOff(), and dmxKeyboardOn().
char* dmxConfigGetXkbOptions (void)
Referenced by dmxDeviceOnOff(), and dmxKeyboardOn().
char* dmxConfigGetXkbRules (void)
Referenced by dmxDeviceOnOff(), and dmxKeyboardOn().
char* dmxConfigGetXkbVariant (void)
Referenced by dmxDeviceOnOff(), and dmxKeyboardOn().
void dmxConfigSetMaxScreens (void)
This function determines the number of displays we WILL have and sets MAXSCREENS to that value. This is difficult since the number depends on the command line (which is easy to count) or on the config file, which has to be parsed.
References dmxConfigConfigure(), dmxDisplaysFromCommandLine, dmxNumScreens, and DMXConfigCmdStruct::filename.
Referenced by ddxProcessArgument().
void dmxConfigSetXkbLayout (const char * layout)
Referenced by ddxProcessArgument(), and dmxConfigCopyFromParam().
void dmxConfigSetXkbModel (const char * model)
Referenced by ddxProcessArgument(), and dmxConfigCopyFromParam().
void dmxConfigSetXkbOptions (const char * options)
Referenced by ddxProcessArgument(), and dmxConfigCopyFromParam().
void dmxConfigSetXkbRules (const char * rules)
Referenced by ddxProcessArgument(), and dmxConfigCopyFromParam().
void dmxConfigSetXkbVariant (const char * variant)
Referenced by ddxProcessArgument(), and dmxConfigCopyFromParam().
void dmxConfigStoreConfig (const char * config)
Make a note that config should be used as the configuration for current instantiation of the DMX server.
References DMXConfigCmdStruct::config, dmxFatal, and dmxLog().
Referenced by ddxProcessArgument().
void dmxConfigStoreDisplay (const char * display)
Make a note that display is the name of an X11 display that should be initialized as a backend (output) display. Called from ddxProcessArgument.
References DMXConfigCmdStruct::displays, dmxDisplaysFromCommandLine, dmxFatal, dmxLog(), DMXConfigListStruct::name, and DMXConfigListStruct::next.
Referenced by ddxProcessArgument().
void dmxConfigStoreFile (const char * file)
Make a note that file is the configuration file.
References dmxFatal, dmxLog(), and DMXConfigCmdStruct::filename.
Referenced by ddxProcessArgument().
void dmxConfigStoreInput (const char * input)
Make a note that input is the name of an X11 display that should be used for input (either a backend or a console input device).
References dmxFatal, dmxLog(), DMXConfigCmdStruct::inputs, DMXConfigListStruct::name, and DMXConfigListStruct::next.
Referenced by ddxProcessArgument().
void dmxConfigStoreXInput (const char * input)
Make a note that input is the name of an X11 display that should be used for input from XInput extension devices.
References dmxFatal, dmxLog(), DMXConfigListStruct::name, DMXConfigListStruct::next, and DMXConfigCmdStruct::xinputs.
Referenced by ddxProcessArgument().
Generated June 29, 2004 for Distributed Multihead X by doxygen 1.3.4.