File Index
dmxscrinit.c File Reference
#include "dmx.h"
#include "dmxsync.h"
#include "dmxshadow.h"
#include "dmxscrinit.h"
#include "dmxcursor.h"
#include "dmxgc.h"
#include "dmxgcops.h"
#include "dmxwindow.h"
#include "dmxpixmap.h"
#include "dmxfont.h"
#include "dmxcmap.h"
#include "dmxprop.h"
#include "dmxdpms.h"
#include "dmxpict.h"
#include "fb.h"
#include "mipointer.h"
#include "micmap.h"
Functions
Bool dmxCloseScreen (int idx, ScreenPtr pScreen)
static Bool dmxSaveScreen (ScreenPtr pScreen, int what)
void dmxBEScreenInit (int idx, ScreenPtr pScreen)
Bool dmxScreenInit (int idx, ScreenPtr pScreen, int argc, char *argv[])
void dmxBECloseScreen (ScreenPtr pScreen)
Variables
static unsigned long dmxGeneration
static unsigned long * dmxCursorGeneration
static int dmxGCPrivateKeyIndex
DevPrivateKey dmxGCPrivateKey = &dmxGCPrivateKeyIndex
static int dmxWinPrivateKeyIndex
DevPrivateKey dmxWinPrivateKey = &dmxWinPrivateKeyIndex
static int dmxPixPrivateKeyIndex
DevPrivateKey dmxPixPrivateKey = &dmxPixPrivateKeyIndex
int dmxFontPrivateIndex
static int dmxScreenPrivateKeyIndex
DevPrivateKey dmxScreenPrivateKey = &dmxScreenPrivateKeyIndex
static int dmxColormapPrivateKeyIndex
DevPrivateKey dmxColormapPrivateKey = &dmxColormapPrivateKeyIndex
static int dmxPictPrivateKeyIndex
DevPrivateKey dmxPictPrivateKey = &dmxPictPrivateKeyIndex
static int dmxGlyphSetPrivateKeyIndex
DevPrivateKey dmxGlyphSetPrivateKey = &dmxGlyphSetPrivateKeyIndex
Detailed Description
This file provides support for screen initialization.
Function Documentation
void dmxBECloseScreen (ScreenPtr pScreen)
Close the pScreen resources on the back-end server.
References _DMXScreenInfo::beDefColormaps, _DMXScreenInfo::beDepths, _DMXScreenInfo::beDisplay, _DMXScreenInfo::beNumDefColormaps, _DMXScreenInfo::beNumPixmapFormats, _DMXScreenInfo::bePixmapFormats, _DMXScreenInfo::beVisuals, dmxDPMSTerm(), dmxScreens, dmxShadowFB, _DMXScreenInfo::noCursor, _DMXScreenInfo::scrnDefDrawables, _DMXScreenInfo::scrnWin, _DMXScreenInfo::shadowFBImage, and _DMXScreenInfo::shadowGC.
Referenced by dmxCloseScreen(), and dmxDetachScreen().
void dmxBEScreenInit (int idx, ScreenPtr pScreen)
Initialize the parts of screen idx that require access to the back-end server.
References _DMXScreenInfo::beBlackPixel, _DMXScreenInfo::beBPP, _DMXScreenInfo::beDefColormaps, _DMXScreenInfo::beDefVisualIndex, _DMXScreenInfo::beDepth, _DMXScreenInfo::beDepths, _DMXScreenInfo::beDisplay, _DMXScreenInfo::beNumDepths, _DMXScreenInfo::beNumPixmapFormats, _DMXScreenInfo::bePixmapFormats, _DMXScreenInfo::beVisuals, _DMXScreenInfo::beWhitePixel, dmxDPMSInit(), dmxPropertyWindow(), dmxScreens, dmxShadowFB, _DMXScreenInfo::noCursor, _DMXScreenInfo::scrnDefDrawables, _DMXScreenInfo::scrnHeight, _DMXScreenInfo::scrnWidth, _DMXScreenInfo::scrnWin, _DMXScreenInfo::scrnX, _DMXScreenInfo::scrnY, _DMXScreenInfo::shadow, _DMXScreenInfo::shadowFBImage, and _DMXScreenInfo::shadowGC.
Referenced by dmxAttachScreen(), and dmxScreenInit().
Bool dmxCloseScreen (int idx, ScreenPtr pScreen)
Close screen number idx.
References _DMXScreenInfo::beDepths, _DMXScreenInfo::beDisplay, _DMXScreenInfo::bePixmapFormats, _DMXScreenInfo::beVisuals, DMX_UNWRAP, dmxBECloseScreen(), dmxResetFonts(), dmxResetRender(), dmxScreens, dmxShadowFB, and _DMXScreenInfo::shadow.
Referenced by dmxScreenInit().
static Bool dmxSaveScreen (ScreenPtr pScreen, int what) [static]
References _DMXScreenInfo::beDisplay, dmxScreens, and dmxSync().
Referenced by dmxScreenInit().
Bool dmxScreenInit (int idx, ScreenPtr pScreen, int argc, char * argv[])
Initialize screen number idx.
References _DMXScreenInfo::beBPP, _DMXScreenInfo::beDefVisualIndex, _DMXScreenInfo::beDepths, _DMXScreenInfo::beNumDepths, _DMXScreenInfo::beNumVisuals, _DMXScreenInfo::beVisuals, _DMXScreenInfo::beXDPI, DMX_WRAP, dmxBEScreenInit(), dmxBitmapToRegion(), dmxChangeBorderWidth(), dmxChangeWindowAttributes(), dmxCloseScreen(), dmxCopyWindow(), dmxCreateColormap(), dmxCreateDefColormap(), dmxCreateGC(), dmxCreatePixmap(), dmxCreateWindow(), dmxCursorGeneration, dmxDestroyColormap(), dmxDestroyPixmap(), dmxDestroyWindow(), dmxFontPrivateIndex, dmxGeneration, dmxGetImage(), dmxGetSpans(), dmxInitGC(), dmxInitPixmap(), dmxInitWindow(), dmxInstallColormap(), dmxPictureInit(), dmxPointerCursorFuncs, dmxPointerSpriteFuncs, dmxPositionWindow(), dmxRealizeFont(), dmxRealizeWindow(), dmxReparentWindow(), dmxResizeWindow(), dmxRestackWindow(), dmxSaveScreen(), dmxScreens, dmxSetShape(), dmxShadowFB, dmxShadowUpdateProc(), dmxStoreColors(), dmxUnrealizeFont(), dmxUnrealizeWindow(), dmxWindowExposures(), _DMXScreenInfo::scrnHeight, _DMXScreenInfo::scrnWidth, and _DMXScreenInfo::shadow.
Referenced by InitOutput().
Variable Documentation
DevPrivateKey dmxColormapPrivateKey = &dmxColormapPrivateKeyIndex
Private index for Colormaps
int dmxColormapPrivateKeyIndex [static]
unsigned long* dmxCursorGeneration [static]
Referenced by dmxScreenInit().
int dmxFontPrivateIndex
Private index for Fonts
Referenced by dmxBEFreeFont(), dmxBELoadFont(), dmxChangeGC(), dmxRealizeFont(), dmxScreenInit(), and dmxUnrealizeFont().
DevPrivateKey dmxGCPrivateKey = &dmxGCPrivateKeyIndex
Private index for GCs
Referenced by dmxInitGC().
int dmxGCPrivateKeyIndex [static]
unsigned long dmxGeneration [static]
Referenced by dmxConsoleUpdatePosition(), dmxMakeUniqueDeviceName(), dmxScreenInit(), dmxSync(), and InitOutput().
DevPrivateKey dmxGlyphSetPrivateKey = &dmxGlyphSetPrivateKeyIndex
Private index for GlyphSets
int dmxGlyphSetPrivateKeyIndex [static]
DevPrivateKey dmxPictPrivateKey = &dmxPictPrivateKeyIndex
Private index for Picts
Referenced by dmxPictureInit().
int dmxPictPrivateKeyIndex [static]
DevPrivateKey dmxPixPrivateKey = &dmxPixPrivateKeyIndex
Private index for Pixmaps
Referenced by dmxInitPixmap().
int dmxPixPrivateKeyIndex [static]
DevPrivateKey dmxScreenPrivateKey = &dmxScreenPrivateKeyIndex
Private index for Screens
Referenced by dmxCloseConsoleScreen(), and dmxConsoleInit().
int dmxScreenPrivateKeyIndex [static]
DevPrivateKey dmxWinPrivateKey = &dmxWinPrivateKeyIndex
Private index for Windows
Referenced by dmxInitWindow().
int dmxWinPrivateKeyIndex [static]
Generated June 29, 2004 for Distributed Multihead X by doxygen 1.3.4.