File Index
usb-keyboard.h File Reference
Functions
void kbdUSBInit (DevicePtr pDev)
void kbdUSBGetInfo (DevicePtr pDev, DMXLocalInitInfoPtr info)
int kbdUSBOn (DevicePtr pDev)
void kbdUSBRead (DevicePtr pDev, dmxMotionProcPtr motion, dmxEnqueueProcPtr enqueue, dmxCheckSpecialProcPtr checkspecial, DMXBlockType block)
void kbdUSBCtrl (DevicePtr pDev, KeybdCtrl *ctrl)
Detailed Description
Interface to USB keyboard driver.
See also:
usb-keyboard.c
usb-common.c
Function Documentation
void kbdUSBCtrl (DevicePtr pDev, KeybdCtrl * ctrl)
Set the LEDs.
References GETPRIV.
void kbdUSBGetInfo (DevicePtr pDev, DMXLocalInitInfoPtr info)
Fill the info structure with information needed to initialize pDev.
References _DMXLocalInitInfo::focusClass, _DMXLocalInitInfo::force, _DMXLocalInitInfo::kbdFeedbackClass, kbdUSBGetMap(), _DMXLocalInitInfo::keyboard, _DMXLocalInitInfo::keyClass, _DMXLocalInitInfo::keySyms, _DMXLocalInitInfo::modMap, and _DMXLocalInitInfo::names.
void kbdUSBInit (DevicePtr pDev)
Initialize pDev using usbInit.
References usbInit(), and usbKeyboard.
Referenced by kbdUSBOn().
int kbdUSBOn (DevicePtr pDev)
Turn pDev on (i.e., take input from pDev).
References GETPRIV, and kbdUSBInit().
void kbdUSBRead (DevicePtr pDev, dmxMotionProcPtr motion, dmxEnqueueProcPtr enqueue, dmxCheckSpecialProcPtr checkspecial, DMXBlockType block)
Generated June 29, 2004 for Distributed Multihead X by doxygen 1.3.4.