LIBRARY = libxkb

CSRCS = \
	XKB.c \
	XKBBind.c \
	XKBCompat.c \
	XKBCtrls.c \
	XKBCvt.c \
	XKBGetMap.c \
	XKBGetByName.c \
	XKBNames.c \
	XKBRdBuf.c \
	XKBSetMap.c \
	XKBUse.c \
	XKBleds.c \
	XKBBell.c \
	XKBGeom.c \
	XKBSetGeom.c \
	XKBExtDev.c \
	XKBList.c \
	XKBMisc.c \
	XKBMAlloc.c \
	XKBGAlloc.c \
	XKBAlloc.c

INCLUDES += ..\..\include\X11 ..\..\src\xlibi18n

