default: all

top_srcdir = ..
include $(top_srcdir)/test/Makefile.sources
include $(top_srcdir)/Makefile.win32.common

TEST_LDADD = \
	$(top_builddir)/pixman/$(CFG_VAR)/$(LIBRARY).lib \
	$(CFG_VAR)/libutils.lib \
	$(NULL)

libutils_OBJECTS = $(patsubst %.c, $(CFG_VAR)/%.obj, $(libutils_sources))

SOURCES = $(patsubst %,   %.c,              $(TESTPROGRAMS) $(BENCHMARKS))
OBJECTS = $(patsubst %.c, $(CFG_VAR)/%.obj, $(SOURCES))
TESTS   = $(patsubst %,   $(CFG_VAR)/%.exe, $(TESTPROGRAMS))
BENCHS  = $(patsubst %,   $(CFG_VAR)/%.exe, $(BENCHMARKS))

all: inform $(TESTS) $(BENCHS)

check: inform $(TESTS)
	@for test in $(TESTS) ; do ./$$test && echo "PASS: $$test" || echo "FAIL: $$test" ; done

$(CFG_VAR)/libutils.lib: $(libutils_OBJECTS)
	@$(AR) $(PIXMAN_ARFLAGS) -OUT:$@ $^

$(CFG_VAR)/%.exe: $(CFG_VAR)/%.obj $(TEST_LDADD)
	@$(LD) $(PIXMAN_LDFLAGS) -OUT:$@ $^

$(top_builddir)/pixman/$(CFG_VAR)/$(LIBRARY).lib:
	@$(MAKE) -C $(top_builddir)/pixman -f Makefile.win32
