LIBRARY = libkdrive

CSRCS =	kaa.c		\
	kaapict.c	\
	kasync.c	\
	kcmap.c		\
	kcurscol.c	\
	kinfo.c		\
	kkeymap.c	\
	kmap.c		\
	kmode.c		\
	knoop.c		\
	koffscreen.c	\
	kshadow.c	\
	kinput.c	\
	kdrive.c	\
	ktest.c



