CSRCS=cfb8bit.c cfb8lineCO.c cfb8lineCP.c cfb8lineG.c cfb8lineX.c cfb8segC.c cfb8segCS.c cfb8segX.c cfb8setG.c \
      cfballpriv.c cfbbitblt.c cfbbltC.c cfbbltG.c cfbbltO.c cfbbltX.c cfbbres.c cfbbresd.c cfbcmap.c cfbcppl.c  \
      cfbfillarcC.c cfbfillarcG.c cfbfillrct.c cfbfillsp.c cfbgc.c cfbgetsp.c cfbglrop8.c cfbhrzvert.c cfbigblt8.c \
      cfbimage.c cfbmskbits.c cfbpixmap.c cfbply1rctC.c cfbply1rctG.c cfbpolypnt.c cfbpush8.c cfbrctstp8.c \
      cfbrrop.c cfbscrinit.c cfbseg.c cfbsetsp.c cfbsolidC.c cfbsolidG.c cfbsolidX.c cfbteblt8.c cfbtegblt.c \
      cfbtile32C.c cfbtile32G.c cfbtileoddC.c cfbtileoddG.c cfbwindow.c cfbzerarcC.c cfbzerarcG.c cfbzerarcX.c
#cfbline.c cfbfillarc.c cfbzerarc.c cfbblt.c cfbsolid.c cfbtileodd.c cfbtile32.c cfb8line.c cfbply1rct.c cfbglblt8.c

LIBRARY=libcfb

