CSRCS=cfb8lineCO.c cfb8lineCP.c cfb8lineG.c cfb8lineX.c cfb8segC.c cfb8segCS.c cfb8segX.c cfb8setG.c cfbbltC.c cfbbltG.c cfbbltO.c \
cfbbltX.c cfbfillarcC.c cfbfillarcG.c cfbply1rctC.c cfbply1rctG.c cfbseg.c cfbsolidC.c cfbsolidG.c cfbsolidX.c cfbtile32C.c cfbtile32G.c \
cfbtileoddC.c cfbtileoddG.c cfbzerarcC.c cfbzerarcG.c cfbzerarcX.c

LIBRARY=libcfb32
