INCLUDES += ..\include\X11\Xft

LIBRARY = libXft

CSRCS = \
                    xftcolor.c \
                    xftcore.c \
                    xftdbg.c \
                    xftdpy.c \
                    xftdraw.c \
                    xftextent.c \
                    xftfont.c \
                    xftfreetype.c \
                    xftglyphs.c \
                    xftinit.c \
                    xftlist.c \
                    xftname.c \
                    xftrender.c \
                    xftstr.c \
                    xftswap.c \
                    xftxlfd.c

INCLUDES += $(MHMAKECONF)\freetype\include $(MHMAKECONF)\fontconfig
